name: 'Azure Pages Build/Deploy'
description: 'Builds and deploys an Azure Pages compatible repository'
inputs:
  app_location:
    description: 'App Location'
    required: false
    default: 'app'
  azure_function_location:
    description: 'Azure Function Location'
    required: false
    default: 'api'
outputs:
  time: # id of output
    description: 'The time we we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app_location }}
    - ${{ inputs.azure_function_location }}